# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True, default='null'),
            preserve_default=False,
        ),
    ]
