# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20160603_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='submitter',
        ),
    ]
