# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-09 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_auto_20160807_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='undefined', max_length=120),
        ),
    ]
