# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
